### ISSUE TITLE
add rest methods for...

### ISSUE THREAD

**Issue by Semior001** [yaattc/automatic-time-table-creation#49]
- [x] list timeslots (timeslots should be hardcoded)
- [ ] big red button for generating timetable (rest method); parameters:
  - from `time` to which `time`?

**Comment by none-word** [comment]
- [  ] <List of rooms>

**Comment by none-word** [comment]
- [x] List of rooms **FORGET ABOUT IT, IT DEPARTMENT WON'T GIVE US A LIST OF ROOMS**
- [x] Get schedule (1 month but will be better if one semester), parameters (Study year and study group)
```JSON
{
    "data": [
        {
            "id": 1,
    		"title": "All Day Event",
    		"start": "2017-02-01"
        },
    	{
            "id": 2,
    		"title": "Long Event",
    		"start": "2017-02-07",
    		"end": "2017-02-10"
        },
    	{
    		"id": 3,
    		"title": "Repeating Event",
    		"start": "2017-02-09T16:00:00"
        },
]
}
```
- [x] API for course creation
